### PR TITLE
fix inkscape plugin for recent inkscape installations

### PR DESCRIPTION
**Pull request by liam-o-marsh**

### CODE REVIEW

**Comment by briling** [comment]
Thanks @liam-o-marsh Liam! Which version is this fix for?

**Comment by liam-o-marsh** [comment]
no clue about which version starts to have problems, but it's necessary for debian11-backports's version of inkscape, so roughly 1.2.2
the only thing to fix was to make the `inx` file capable of finding the python script

**Comment by liam-o-marsh** [comment]
...I was mistaken on that, I'll need to check on monday
the PC in front of me does have 1.2.2 and it doesn't work, let me fix that.

**Comment by liam-o-marsh** [comment]
looking at the right PC, this fix is for inkscape 1.0.2
I have a couple other fixes ready for 1.2.2 as well on my home PC, but for now they are mixed with a lot of refactoring and an (incomplete) attempt to add other bond-creation methods to have long-range bonds not take half of each bubble

**Comment by briling** [comment]
Thanks!
Yeah, it doesn't work for 1.2.x, but I never had time to fix it...

**Pull request merged**
